# GitHub Actions yml 파일의 이름
name: Hello World

# Actions 이벤트 동작 조건
on:
# push 및 PR 하는 브랜치 지정
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 이벤트 발생 시 일어나는 일
jobs: 
  build:
    # 이벤트 발생 시 구동되는 컴퓨터의 os 
    runs-on: ubuntu-latest

    # 실제로 일어나는 일 명세
    steps:
      # - uses: actions/checkout@v3
      - name : Run pwd
        run : pwd
        
      - name : Run ls -al
        run : ls -al
